stomp.py: stomp.bridge.bridge.StompConnection Class Reference
stomp.bridge.bridge.StompConnection Class Reference
Public Member Functions
def __init__
def send_error
def send
def run
def shutdown
Public Attributes
server
conn
addr
running
id
Constructor & Destructor Documentation
def stomp.bridge.bridge.StompConnection.__init__ (self, server, conn, addr)
Member Function Documentation
def stomp.bridge.bridge.StompConnection.run (self)
def stomp.bridge.bridge.StompConnection.send (self, msg)
Referenced by stomp.bridge.bridge.StompConnection.send_error().
def stomp.bridge.bridge.StompConnection.send_error (self, msg)
Referenced by stomp.bridge.bridge.StompConnection.run().
def stomp.bridge.bridge.StompConnection.shutdown (self)
Referenced by stomp.bridge.bridge.StompConnection.run().
Member Data Documentation
stomp.bridge.bridge.StompConnection.addr
stomp.bridge.bridge.StompConnection.conn
Referenced by stomp.bridge.bridge.StompConnection.send().
stomp.bridge.bridge.StompConnection.id
stomp.bridge.bridge.StompConnection.running
Referenced by stomp.transport.Transport.disconnect_socket(), stomp.listener.HeartbeatListener.on_send(), stomp.bridge.bridge.StompConnection.run(), stomp.transport.Transport.send_frame(), and stomp.bridge.bridge.StompConnection.shutdown().
stomp.bridge.bridge.StompConnection.server
The documentation for this class was generated from the following file:
stomp/bridge/bridge.py