stomp.py: stomp.transport.BaseTransport Class Reference
stomp.transport.BaseTransport Class Reference
Public Member Functions
def __init__ (self, wait_on_receipt)
def override_threading (self, create_thread_fc)
Override for thread creation.
def start (self)
Start the connection.
def stop (self)
Stop the connection.
def is_connected (self)
def set_connected (self, connected)
def set_listener (self, name, listener)
Set a named listener to use with this connection.
def remove_listener (self, name)
Remove a listener according to the specified name.
def get_listener (self, name)
Return the named listener.
def process_frame (self, f, frame_str)
def notify
Utility function for notifying listeners of incoming and outgoing messages.
def transmit (self, frame)
Convert a frame object to a frame string and transmit to the server.
def send (self, frame)
def receive (self)
def cleanup (self)
def attempt_connection (self)
def wait_for_connection
Wait until we've established a connection with the server.
Public Member Functions inherited from stomp.listener.Publisher
def set_listener (self, name, listener)
Set a named listener to use with this connection.
def remove_listener (self, name)
Remove a listener according to the specified name.
def get_listener (self, name)
Return the named listener.
Public Attributes
listeners
running
blocking
connected
connection_error
create_thread_fc
Constructor & Destructor Documentation
def stomp.transport.BaseTransport.__init__ (self, wait_on_receipt)
Parameters
wait_on_receipt if a receipt is specified, then the send method should wait (block) for the server to respond with that receipt-id before continuing
Member Function Documentation
def stomp.transport.BaseTransport.attempt_connection (self)
Referenced by stomp.transport.BaseTransport.start().
def stomp.transport.BaseTransport.cleanup (self)
Referenced by stomp.transport.BaseTransport.wait_for_connection().
def stomp.transport.BaseTransport.get_listener (self, name)
Return the named listener.
Parameters
name the listener to return
def stomp.transport.BaseTransport.is_connected (self)
Referenced by stomp.transport.BaseTransport.wait_for_connection().
def stomp.transport.BaseTransport.notify (self, frame_type, headers = None, body = None)
Utility function for notifying listeners of incoming and outgoing messages.
Parameters
frame_type the type of message
headers the map of headers associated with the message
body the content of the message
Referenced by stomp.adapter.multicast.MulticastTransport.process_frame(), stomp.transport.BaseTransport.process_frame(), stomp.adapter.multicast.MulticastConnection.send_frame(), stomp.transport.BaseTransport.start(), and stomp.transport.BaseTransport.wait_for_connection().
def stomp.transport.BaseTransport.override_threading (self, create_thread_fc)
Override for thread creation.
Use an alternate threading library by setting this to a function with a single argument (which is the receiver loop callback). The thread which is returned should be started (ready to run)
def stomp.transport.BaseTransport.process_frame (self, f, frame_str)
Referenced by stomp.transport.BaseTransport.wait_for_connection().
def stomp.transport.BaseTransport.receive (self)
Referenced by stomp.transport.BaseTransport.wait_for_connection().
def stomp.transport.BaseTransport.remove_listener (self, name)
Remove a listener according to the specified name.
Parameters
name the name of the listener to remove
def stomp.transport.BaseTransport.send (self, frame)
Referenced by stomp.transport.BaseTransport.transmit().
def stomp.transport.BaseTransport.set_connected (self, connected)
Referenced by stomp.transport.BaseTransport.notify().
def stomp.transport.BaseTransport.set_listener (self, name, listener)
Set a named listener to use with this connection.
See also
listener::ConnectionListener
Parameters
name the name of the listener
listener the listener object
def stomp.transport.BaseTransport.start (self)
Start the connection.
This should be called after all listeners have been registered. If this method is not called, no frames will be received by the connection.
def stomp.transport.BaseTransport.stop (self)
Stop the connection.
Performs a clean shutdown by waiting for the receiver thread to exit.
def stomp.transport.BaseTransport.transmit (self, frame)
Convert a frame object to a frame string and transmit to the server.
def stomp.transport.BaseTransport.wait_for_connection (self, timeout = None)
Wait until we've established a connection with the server.
Member Data Documentation
stomp.transport.BaseTransport.blocking
stomp.transport.BaseTransport.connected
Referenced by stomp.transport.BaseTransport.is_connected(), stomp.transport.BaseTransport.notify(), and stomp.transport.BaseTransport.set_connected().
stomp.transport.BaseTransport.connection_error
Referenced by stomp.transport.BaseTransport.notify(), and stomp.transport.BaseTransport.wait_for_connection().
stomp.transport.BaseTransport.create_thread_fc
Referenced by stomp.transport.BaseTransport.override_threading(), and stomp.transport.BaseTransport.start().
stomp.transport.BaseTransport.listeners
Referenced by stomp.transport.BaseTransport.get_listener(), stomp.transport.BaseTransport.remove_listener(), and stomp.transport.BaseTransport.set_listener().
stomp.transport.BaseTransport.running
Referenced by stomp.transport.BaseTransport.start(), and stomp.transport.BaseTransport.wait_for_connection().
The documentation for this class was generated from the following file:
stomp/transport.py