stomp.py: stomp.protocol.Protocol10 Class Reference
stomp.protocol.Protocol10 Class Reference
Version 1.0 of the protocol.
Public Member Functions
def __init__ (self, transport)
def send_frame
def abort (self, transaction, headers={}, keyword_headers)
def ack
def begin (self, transaction=None, headers={}, keyword_headers)
def commit (self, transaction=None, headers={}, keyword_headers)
def connect (self, username=None, passcode=None, wait=False, headers={}, keyword_headers)
def disconnect (self, receipt=str(uuid.uuid4()), headers={}, keyword_headers)
def send (self, destination, body, content_type=None, headers={}, keyword_headers)
def subscribe (self, destination, id=None, ack='auto', headers={}, keyword_headers)
def unsubscribe (self, destination=None, id=None, headers={}, keyword_headers)
Public Member Functions inherited from stomp.listener.ConnectionListener
def on_connecting (self, host_and_port)
Called by the STOMP connection once a TCP/IP connection to the STOMP server has been established or re-established.
def on_connected (self, headers, body)
Called by the STOMP connection when a CONNECTED frame is received, that is after a connection has been established or re-established.
def on_disconnected (self)
Called by the STOMP connection when a TCP/IP connection to the STOMP server has been lost.
def on_heartbeat_timeout (self)
Called by the STOMP connection when a heartbeat message has not been received beyond the specified period.
def on_before_message (self, headers, body)
Called by the STOMP connection before a message is returned to the client app.
def on_message (self, headers, body)
Called by the STOMP connection when a MESSAGE frame is received.
def on_receipt (self, headers, body)
Called by the STOMP connection when a RECEIPT frame is received, sent by the server if requested by the client using the 'receipt' header.
def on_error (self, headers, body)
Called by the STOMP connection when an ERROR frame is received.
def on_send (self, frame)
Called by the STOMP connection when it is in the process of sending a message.
def on_heartbeat (self)
Called on receipt of a heartbeat.
Public Attributes
transport
version
Detailed Description
Version 1.0 of the protocol.
Constructor & Destructor Documentation
def stomp.protocol.Protocol10.__init__ (self, transport)
Member Function Documentation
def stomp.protocol.Protocol10.abort (self, transaction, headers = {}, keyword_headers)
def stomp.protocol.Protocol10.ack (self, id, transaction = None)
def stomp.protocol.Protocol10.begin (self, transaction = None, headers = {}, keyword_headers)
def stomp.protocol.Protocol10.commit (self, transaction = None, headers = {}, keyword_headers)
def stomp.protocol.Protocol10.connect (self, username = None, passcode = None, wait = False, headers = {}, keyword_headers)
def stomp.protocol.Protocol10.disconnect (self, receipt = str(uuid.uuid4()), headers = {}, keyword_headers)
def stomp.protocol.Protocol10.send (self, destination, body, content_type = None, headers = {}, keyword_headers)
Referenced by stomp.transport.BaseTransport.transmit().
def stomp.protocol.Protocol10.send_frame (self, cmd, headers = {}, body = '')
Referenced by stomp.protocol.Protocol10.abort(), stomp.protocol.Protocol11.abort(), stomp.protocol.Protocol10.ack(), stomp.protocol.Protocol11.ack(), stomp.protocol.Protocol12.ack(), stomp.protocol.Protocol10.begin(), stomp.protocol.Protocol11.begin(), stomp.protocol.Protocol10.commit(), stomp.protocol.Protocol11.commit(), stomp.protocol.Protocol10.connect(), stomp.protocol.Protocol11.connect(), stomp.protocol.Protocol12.connect(), stomp.protocol.Protocol10.disconnect(), stomp.protocol.Protocol11.disconnect(), stomp.protocol.Protocol11.nack(), stomp.protocol.Protocol12.nack(), stomp.protocol.Protocol10.send(), stomp.protocol.Protocol11.send(), stomp.protocol.Protocol10.subscribe(), stomp.protocol.Protocol11.subscribe(), stomp.protocol.Protocol10.unsubscribe(), and stomp.protocol.Protocol11.unsubscribe().
def stomp.protocol.Protocol10.subscribe (self, destination, id = None, ack = 'auto', headers = {}, keyword_headers)
def stomp.protocol.Protocol10.unsubscribe (self, destination = None, id = None, headers = {}, keyword_headers)
Member Data Documentation
stomp.protocol.Protocol10.transport
stomp.protocol.Protocol10.version
Referenced by stomp.protocol.Protocol10.connect(), stomp.protocol.Protocol11.connect(), and stomp.protocol.Protocol12.connect().
The documentation for this class was generated from the following file:
stomp/protocol.py