stomp.py: stomp.adapter.multicast.MulticastConnection Class Reference
stomp.adapter.multicast.MulticastConnection Class Reference
Public Member Functions
def __init__
def connect (self, username=None, passcode=None, wait=False, headers={}, keyword_headers)
def subscribe (self, destination, id, ack='auto', headers={}, keyword_headers)
def unsubscribe (self, id, headers={}, keyword_headers)
def disconnect (self, receipt=str(uuid.uuid4()), headers={}, keyword_headers)
def send_frame
Public Member Functions inherited from stomp.connect.BaseConnection
def __init__ (self, transport)
def set_listener (self, name, listener)
def remove_listener (self, name)
def get_listener (self, name)
def start (self)
def stop (self)
def is_connected (self)
def set_ssl (self, args, kwargs)
def get_ssl (self, args, kwargs)
Public Member Functions inherited from stomp.listener.Publisher
def set_listener (self, name, listener)
Set a named listener to use with this connection.
def remove_listener (self, name)
Remove a listener according to the specified name.
def get_listener (self, name)
Return the named listener.
Public Member Functions inherited from stomp.protocol.Protocol12
def __init__ (self, transport, heartbeats=(0, 0)
def send_frame
def ack
def nack
def connect (self, username=None, passcode=None, wait=False, headers={}, keyword_headers)
Send a STOMP CONNECT frame.
Public Member Functions inherited from stomp.protocol.Protocol11
def __init__ (self, transport, heartbeats=(0, 0)
def send_frame
def abort (self, transaction, headers={}, keyword_headers)
def ack
def begin (self, transaction=None, headers={}, keyword_headers)
def commit (self, transaction=None, headers={}, keyword_headers)
def connect (self, username=None, passcode=None, wait=False, headers={}, keyword_headers)
def disconnect (self, receipt=str(uuid.uuid4()), headers={}, keyword_headers)
def nack
def send (self, destination, body, content_type=None, headers={}, keyword_headers)
def subscribe (self, destination, id, ack='auto', headers={}, keyword_headers)
def unsubscribe (self, id, headers={}, keyword_headers)
Public Member Functions inherited from stomp.listener.HeartbeatListener
def __init__ (self, heartbeats)
def on_connected (self, headers, body)
Once the connection is established, and 'heart-beat' is found in the headers, we calculate the real heartbeat numbers (based on what the server sent and what was specified by the client) - if the heartbeats are not 0, we start up the heartbeat loop accordingly.
def on_disconnected (self)
def on_message (self, headers, body)
Reset the last received time whenever a message is received.
def on_heartbeat (self)
Reset the last received time whenever a heartbeat message is received.
def on_send (self, frame)
Add the heartbeat header to the frame when connecting.
Public Member Functions inherited from stomp.listener.ConnectionListener
def on_connecting (self, host_and_port)
Called by the STOMP connection once a TCP/IP connection to the STOMP server has been established or re-established.
def on_connected (self, headers, body)
Called by the STOMP connection when a CONNECTED frame is received, that is after a connection has been established or re-established.
def on_disconnected (self)
Called by the STOMP connection when a TCP/IP connection to the STOMP server has been lost.
def on_heartbeat_timeout (self)
Called by the STOMP connection when a heartbeat message has not been received beyond the specified period.
def on_before_message (self, headers, body)
Called by the STOMP connection before a message is returned to the client app.
def on_message (self, headers, body)
Called by the STOMP connection when a MESSAGE frame is received.
def on_receipt (self, headers, body)
Called by the STOMP connection when a RECEIPT frame is received, sent by the server if requested by the client using the 'receipt' header.
def on_error (self, headers, body)
Called by the STOMP connection when an ERROR frame is received.
def on_send (self, frame)
Called by the STOMP connection when it is in the process of sending a message.
def on_heartbeat (self)
Called on receipt of a heartbeat.
Public Attributes
transport
transactions
Public Attributes inherited from stomp.connect.BaseConnection
transport
Public Attributes inherited from stomp.protocol.Protocol12
version
Public Attributes inherited from stomp.protocol.Protocol11
transport
version
Public Attributes inherited from stomp.listener.HeartbeatListener
connected
running
heartbeats
received_heartbeat
heartbeat_thread
send_sleep
receive_sleep
sleep_time
Constructor & Destructor Documentation
def stomp.adapter.multicast.MulticastConnection.__init__ (self, wait_on_receipt = False)
Member Function Documentation
def stomp.adapter.multicast.MulticastConnection.connect (self, username = None, passcode = None, wait = False, headers = {}, keyword_headers)
def stomp.adapter.multicast.MulticastConnection.disconnect (self, receipt = str(uuid.uuid4()), headers = {}, keyword_headers)
def stomp.adapter.multicast.MulticastConnection.send_frame (self, cmd, headers = {}, body = '')
Referenced by stomp.protocol.Protocol10.abort(), stomp.protocol.Protocol11.abort(), stomp.protocol.Protocol10.ack(), stomp.protocol.Protocol11.ack(), stomp.protocol.Protocol12.ack(), stomp.protocol.Protocol10.begin(), stomp.protocol.Protocol11.begin(), stomp.protocol.Protocol10.commit(), stomp.protocol.Protocol11.commit(), stomp.protocol.Protocol10.connect(), stomp.protocol.Protocol11.connect(), stomp.protocol.Protocol12.connect(), stomp.protocol.Protocol10.disconnect(), stomp.protocol.Protocol11.disconnect(), stomp.protocol.Protocol11.nack(), stomp.protocol.Protocol12.nack(), stomp.protocol.Protocol10.send(), stomp.protocol.Protocol11.send(), stomp.protocol.Protocol10.subscribe(), stomp.protocol.Protocol11.subscribe(), stomp.protocol.Protocol10.unsubscribe(), and stomp.protocol.Protocol11.unsubscribe().
def stomp.adapter.multicast.MulticastConnection.subscribe (self, destination, id, ack = 'auto', headers = {}, keyword_headers)
def stomp.adapter.multicast.MulticastConnection.unsubscribe (self, id, headers = {}, keyword_headers)
Member Data Documentation
stomp.adapter.multicast.MulticastConnection.transactions
Referenced by stomp.adapter.multicast.MulticastConnection.send_frame().
stomp.adapter.multicast.MulticastConnection.transport
The documentation for this class was generated from the following file:
stomp/adapter/multicast.py