stomp.py: stomp.__main__.StompCLI Class Reference
stomp.__main__.StompCLI Class Reference
A command line interface to the stomp.py client.
Public Member Functions
def __init__
def on_connecting (self, host_and_port)
def on_disconnected (self)
def on_message (self, headers, body)
def on_error (self, headers, body)
def on_receipt (self, headers, body)
def on_connected (self, headers, body)
def help_help (self)
def default (self, line)
def emptyline (self)
def help
def do_quit (self, args)
def help_quit (self)
def help_EOF (self)
def do_subscribe (self, args)
def help_subscribe (self)
def do_unsubscribe (self, args)
def help_unsubscribe (self)
def do_send (self, args)
def complete_send (self, text, line, begidx, endidx)
def help_send (self)
def do_sendrec (self, args)
def help_sendrec (self)
def do_sendreply (self, args)
def help_sendreply (self)
def do_sendfile (self, args)
def help_sendfile (self)
def do_version (self, args)
def help_version (self)
def check_ack_nack (self, cmd, args)
def do_ack (self, args)
def help_ack (self)
def do_nack (self, args)
def help_nack (self)
def do_abort (self, args)
def help_abort (self)
def do_begin (self, args)
def help_begin (self)
def do_commit (self, args)
def help_commit (self)
def do_stats (self, args)
def help_stats (self)
def do_run (self, args)
def help_run (self)
Public Member Functions inherited from stomp.listener.ConnectionListener
def on_connecting (self, host_and_port)
Called by the STOMP connection once a TCP/IP connection to the STOMP server has been established or re-established.
def on_connected (self, headers, body)
Called by the STOMP connection when a CONNECTED frame is received, that is after a connection has been established or re-established.
def on_disconnected (self)
Called by the STOMP connection when a TCP/IP connection to the STOMP server has been lost.
def on_heartbeat_timeout (self)
Called by the STOMP connection when a heartbeat message has not been received beyond the specified period.
def on_before_message (self, headers, body)
Called by the STOMP connection before a message is returned to the client app.
def on_message (self, headers, body)
Called by the STOMP connection when a MESSAGE frame is received.
def on_receipt (self, headers, body)
Called by the STOMP connection when a RECEIPT frame is received, sent by the server if requested by the client using the 'receipt' header.
def on_error (self, headers, body)
Called by the STOMP connection when an ERROR frame is received.
def on_send (self, frame)
Called by the STOMP connection when it is in the process of sending a message.
def on_heartbeat (self)
Called on receipt of a heartbeat.
Public Attributes
prompt
verbose
user
passcode
conn
transaction_id
version
Static Public Attributes
do_exit = do_quit
do_EOF = do_quit
help_exit = help_quit
complete_unsubscribe = complete_send
complete_sendrec = complete_send
complete_sendreply = complete_send
complete_sendfile = complete_send
do_ver = do_version
help_ver = help_version
do_rollback = do_abort
help_rollback = help_abort
Detailed Description
A command line interface to the stomp.py client.
See stomp::connect::StompConnection11 for more information on establishing a connection to a stomp server.
Constructor & Destructor Documentation
def stomp.__main__.StompCLI.__init__ (self, host = 'localhost', port = 61613, user = '', passcode = '', ver = '1.1', prompt = '> ', verbose = True, stdin = sys.stdin, stdout = sys.stdout)
Member Function Documentation
def stomp.__main__.StompCLI.check_ack_nack (self, cmd, args)
Referenced by stomp.__main__.StompCLI.do_ack(), and stomp.__main__.StompCLI.do_nack().
def stomp.__main__.StompCLI.complete_send (self, text, line, begidx, endidx)
def stomp.__main__.StompCLI.default (self, line)
def stomp.__main__.StompCLI.do_abort (self, args)
def stomp.__main__.StompCLI.do_ack (self, args)
def stomp.__main__.StompCLI.do_begin (self, args)
def stomp.__main__.StompCLI.do_commit (self, args)
def stomp.__main__.StompCLI.do_nack (self, args)
def stomp.__main__.StompCLI.do_quit (self, args)
def stomp.__main__.StompCLI.do_run (self, args)
def stomp.__main__.StompCLI.do_send (self, args)
def stomp.__main__.StompCLI.do_sendfile (self, args)
def stomp.__main__.StompCLI.do_sendrec (self, args)
def stomp.__main__.StompCLI.do_sendreply (self, args)
def stomp.__main__.StompCLI.do_stats (self, args)
def stomp.__main__.StompCLI.do_subscribe (self, args)
def stomp.__main__.StompCLI.do_unsubscribe (self, args)
def stomp.__main__.StompCLI.do_version (self, args)
def stomp.__main__.StompCLI.emptyline (self)
def stomp.__main__.StompCLI.help (self, usage, description, required = [], optional = [])
Referenced by stomp.__main__.StompCLI.help_abort(), stomp.__main__.StompCLI.help_ack(), stomp.__main__.StompCLI.help_begin(), stomp.__main__.StompCLI.help_commit(), stomp.__main__.StompCLI.help_nack(), stomp.__main__.StompCLI.help_quit(), stomp.__main__.StompCLI.help_run(), stomp.__main__.StompCLI.help_send(), stomp.__main__.StompCLI.help_sendfile(), stomp.__main__.StompCLI.help_sendrec(), stomp.__main__.StompCLI.help_sendreply(), stomp.__main__.StompCLI.help_stats(), stomp.__main__.StompCLI.help_subscribe(), stomp.__main__.StompCLI.help_unsubscribe(), and stomp.__main__.StompCLI.help_version().
def stomp.__main__.StompCLI.help_abort (self)
def stomp.__main__.StompCLI.help_ack (self)
def stomp.__main__.StompCLI.help_begin (self)
def stomp.__main__.StompCLI.help_commit (self)
def stomp.__main__.StompCLI.help_EOF (self)
def stomp.__main__.StompCLI.help_help (self)
def stomp.__main__.StompCLI.help_nack (self)
def stomp.__main__.StompCLI.help_quit (self)
def stomp.__main__.StompCLI.help_run (self)
def stomp.__main__.StompCLI.help_send (self)
def stomp.__main__.StompCLI.help_sendfile (self)
def stomp.__main__.StompCLI.help_sendrec (self)
def stomp.__main__.StompCLI.help_sendreply (self)
def stomp.__main__.StompCLI.help_stats (self)
def stomp.__main__.StompCLI.help_subscribe (self)
def stomp.__main__.StompCLI.help_unsubscribe (self)
def stomp.__main__.StompCLI.help_version (self)
def stomp.__main__.StompCLI.on_connected (self, headers, body)
See also
ConnectionListener::on_connected
def stomp.__main__.StompCLI.on_connecting (self, host_and_port)
See also
ConnectionListener::on_connecting
def stomp.__main__.StompCLI.on_disconnected (self)
See also
ConnectionListener::on_disconnected
def stomp.__main__.StompCLI.on_error (self, headers, body)
See also
ConnectionListener::on_error
def stomp.__main__.StompCLI.on_message (self, headers, body)
See also
ConnectionListener::on_message
Special case: if the header 'filename' is present, the content is written out as a file
def stomp.__main__.StompCLI.on_receipt (self, headers, body)
See also
ConnectionListener::on_receipt
Member Data Documentation
stomp.__main__.StompCLI.complete_sendfile = complete_send static
stomp.__main__.StompCLI.complete_sendrec = complete_send static
stomp.__main__.StompCLI.complete_sendreply = complete_send static
stomp.__main__.StompCLI.complete_unsubscribe = complete_send static
stomp.__main__.StompCLI.conn
stomp.__main__.StompCLI.do_EOF = do_quit static
stomp.__main__.StompCLI.do_exit = do_quit static
stomp.__main__.StompCLI.do_rollback = do_abort static
stomp.__main__.StompCLI.do_ver = do_version static
stomp.__main__.StompCLI.help_exit = help_quit static
stomp.__main__.StompCLI.help_rollback = help_abort static
stomp.__main__.StompCLI.help_ver = help_version static
stomp.__main__.StompCLI.passcode
stomp.__main__.StompCLI.prompt
stomp.__main__.StompCLI.transaction_id
Referenced by stomp.__main__.StompCLI.do_abort(), stomp.__main__.StompCLI.do_ack(), stomp.__main__.StompCLI.do_begin(), stomp.__main__.StompCLI.do_commit(), stomp.__main__.StompCLI.do_nack(), stomp.__main__.StompCLI.do_send(), stomp.__main__.StompCLI.do_sendfile(), and stomp.__main__.StompCLI.do_sendrec().
stomp.__main__.StompCLI.user
stomp.__main__.StompCLI.verbose
stomp.__main__.StompCLI.version
Referenced by stomp.__main__.StompCLI.check_ack_nack(), stomp.protocol.Protocol10.connect(), stomp.protocol.Protocol11.connect(), and stomp.protocol.Protocol12.connect().
The documentation for this class was generated from the following file:
stomp/__main__.py