stomp.py: stomp.transport.Transport Class Reference
stomp.transport.Transport Class Reference
Represents a STOMP client 'transport'.
Public Member Functions
def __init__
def override_threading
Override for thread creation.
def start
Start the connection.
def stop
Stop the connection.
def is_connected
Return true if the socket managed by this connection is connected.
def set_connected
def set_listener
Set a named listener to use with this connection.
def remove_listener
Remove a listener according to the specified name.
def get_listener
Return the named listener.
def disconnect_socket
Disconnect the underlying socket connection.
def transmit
Convert a frame object to a frame string and transmit to the server.
def send_over_socket
def read_from_socket
def process_frame
def notify
Utility function for notifying listeners of incoming and outgoing messages.
def attempt_connection
Try connecting to the (host, port) tuples specified at construction time.
def wait_for_connection
Wait until we've established a connection with the server.
def set_ssl
Sets up SSL configuration for the given hosts.
def get_ssl
Get SSL params for the given host.
Public Member Functions inherited from stomp.listener.Publisher
def set_listener
Set a named listener to use with this connection.
def remove_listener
Remove a listener according to the specified name.
def get_listener
Return the named listener.
Public Attributes
listeners
socket
current_host_and_port
blocking
connected
connection_error
create_thread_fc
vhost
running
Detailed Description
Represents a STOMP client 'transport'.
Effectively this is the communications mechanism without the definition of the protocol.
Constructor & Destructor Documentation
def stomp.transport.Transport.__init__ (self, host_and_ports = [ ('localhost', 61613, prefer_localhost = True, try_loopback_connect = True, reconnect_sleep_initial = 0.1, reconnect_sleep_increase = 0.5, reconnect_sleep_jitter = 0.1, reconnect_sleep_max = 60.0, reconnect_attempts_max = 3, use_ssl = False, ssl_key_file = None, ssl_cert_file = None, ssl_ca_certs = None, ssl_cert_validator = None, wait_on_receipt = False, ssl_version = None, timeout = None, keepalive = None, vhost = None)
Parameters
host_and_ports a list of (host, port) tuples.
prefer_localhost if True and the local host is mentioned in the (host, port) tuples, try to connect to this first
try_loopback_connect if True and the local host is found in the host tuples, try connecting to it using loopback interface (127.0.0.1)
reconnect_sleep_initial initial delay in seconds to wait before reattempting to establish a connection if connection to any of the hosts fails.
reconnect_sleep_increase factor by which the sleep delay is increased after each connection attempt. For example, 0.5 means to wait 50% longer than before the previous attempt, 1.0 means wait twice as long, and 0.0 means keep the delay constant.
reconnect_sleep_max maximum delay between connection attempts, regardless of the reconnect_sleep_increase.
reconnect_sleep_jitter random additional time to wait (as a percentage of the time determined using the previous parameters) between connection attempts in order to avoid stampeding. For example, a value of 0.1 means to wait an extra 0%-10% (randomly determined) of the delay calculated using the previous three parameters.
reconnect_attempts_max maximum attempts to reconnect
use_ssl deprecated, see Transport::set_ssl
ssl_cert_file deprecated, see Transport::set_ssl
ssl_key_file deprecated, see Transport::set_ssl
ssl_ca_certs deprecated, see Transport::set_ssl
ssl_cert_validator deprecated, see Transport::set_ssl
wait_on_receipt if a receipt is specified, then the send method should wait (block) for the server to respond with that receipt-id before continuing
ssl_version deprecated, see Transport::set_ssl
timeout the timeout value to use when connecting the stomp socket
keepalive some operating systems support sending the occasional heart beat packets to detect when a connection fails. This parameter can either be set set to a boolean to turn on the default keepalive options for your OS, or as a tuple of values, which also enables keepalive packets, but specifies options specific to your OS implementation
vhost specify a virtual hostname to provide in the 'host' header of the connection
Member Function Documentation
def stomp.transport.Transport.attempt_connection (self)
Try connecting to the (host, port) tuples specified at construction time.
def stomp.transport.Transport.disconnect_socket (self)
Disconnect the underlying socket connection.
Referenced by stomp.transport.Transport.notify().
def stomp.transport.Transport.get_listener (self, name)
Return the named listener.
Parameters
name the listener to return
def stomp.transport.Transport.get_ssl (self, host_and_port = None)
Get SSL params for the given host.
Parameters
host_and_port The host/port pair we want SSL params for, default current_host_port
Referenced by stomp.transport.Transport.attempt_connection().
def stomp.transport.Transport.is_connected (self)
Return true if the socket managed by this connection is connected.
Referenced by stomp.transport.Transport.wait_for_connection().
def stomp.transport.Transport.notify (self, frame_type, headers = None, body = None)
Utility function for notifying listeners of incoming and outgoing messages.
Parameters
frame_type the type of message
headers the map of headers associated with the message
body the content of the message
Referenced by stomp.transport.Transport.notify(), stomp.adapter.multicast.MulticastTransport.process_frame(), stomp.transport.Transport.process_frame(), and stomp.adapter.multicast.MulticastConnection.send_frame().
def stomp.transport.Transport.override_threading (self, create_thread_fc)
Override for thread creation.
Use an alternate threading library by setting this to a function with a single argument (which is the receiver loop callback). The thread which is returned should be started (ready to run)
def stomp.transport.Transport.process_frame (self, f, frame_str)
Referenced by stomp.transport.Transport.notify().
def stomp.transport.Transport.read_from_socket (self)
Referenced by stomp.transport.Transport.notify().
def stomp.transport.Transport.remove_listener (self, name)
Remove a listener according to the specified name.
Parameters
name the name of the listener to remove
def stomp.transport.Transport.send_over_socket (self, encoded_frame)
Referenced by stomp.transport.Transport.transmit().
def stomp.transport.Transport.set_connected (self, connected)
Referenced by stomp.transport.Transport.notify().
def stomp.transport.Transport.set_listener (self, name, listener)
Set a named listener to use with this connection.
See Also
listener::ConnectionListener
Parameters
name the name of the listener
listener the listener object
def stomp.transport.Transport.set_ssl (self, for_hosts = [], key_file = None, cert_file = None, ca_certs = None, cert_validator = None, ssl_version = DEFAULT_SSL_VERSION)
Sets up SSL configuration for the given hosts.
This ensures socket is wrapped in a SSL connection, raising an exception if the SSL module can't be found.
Parameters
for_hosts hosts this SSL configuration should be applied to
cert_file the path to a X509 certificate
key_file the path to a X509 key file
ca_certs the path to the a file containing CA certificates to validate the server against. If this is not set, server side certificate validation is not done.
cert_validator function which performs extra validation on the client certificate, for example checking the returned certificate has a commonName attribute equal to the hostname (to avoid man in the middle attacks). The signature is: (OK, err_msg) = validation_function(cert, hostname) where OK is a boolean, and cert is a certificate structure as returned by ssl.SSLSocket.getpeercert()
ssl_version SSL protocol to use for the connection. This should be one of the PROTOCOL_x constants provided by the ssl module. The default is ssl.PROTOCOL_SSLv3
Referenced by stomp.transport.Transport.wait_for_connection().
def stomp.transport.Transport.start (self)
Start the connection.
This should be called after all listeners have been registered. If this method is not called, no frames will be received by the connection.
def stomp.transport.Transport.stop (self)
Stop the connection.
Performs a clean shutdown by waiting for the receiver thread to exit.
def stomp.transport.Transport.transmit (self, frame)
Convert a frame object to a frame string and transmit to the server.
def stomp.transport.Transport.wait_for_connection (self, timeout = None)
Wait until we've established a connection with the server.
Member Data Documentation
stomp.transport.Transport.blocking
Referenced by stomp.transport.Transport.attempt_connection().
stomp.transport.Transport.connected
Referenced by stomp.transport.Transport.is_connected(), stomp.transport.Transport.notify(), and stomp.transport.Transport.set_connected().
stomp.transport.Transport.connection_error
Referenced by stomp.transport.Transport.attempt_connection(), stomp.transport.Transport.notify(), and stomp.transport.Transport.wait_for_connection().
stomp.transport.Transport.create_thread_fc
Referenced by stomp.transport.Transport.override_threading().
stomp.transport.Transport.current_host_and_port
Referenced by stomp.transport.Transport.attempt_connection(), stomp.transport.Transport.disconnect_socket(), stomp.transport.Transport.get_ssl(), stomp.transport.Transport.notify(), and stomp.transport.Transport.set_ssl().
stomp.transport.Transport.listeners
Referenced by stomp.transport.Transport.get_listener(), stomp.transport.Transport.remove_listener(), and stomp.transport.Transport.set_listener().
stomp.transport.Transport.running
Referenced by stomp.transport.Transport.attempt_connection(), stomp.transport.Transport.disconnect_socket(), and stomp.transport.Transport.notify().
stomp.transport.Transport.socket
Referenced by stomp.transport.Transport.attempt_connection(), stomp.transport.Transport.disconnect_socket(), stomp.transport.Transport.is_connected(), stomp.transport.Transport.notify(), and stomp.transport.Transport.transmit().
stomp.transport.Transport.vhost
The documentation for this class was generated from the following file:
stomp/transport.py