stomp.py: stomp.backward2 Namespace Reference
stomp.backward2 Namespace Reference
Python2-specific versions of various functions used by stomp.py.
Functions
def input_prompt (prompt)
Get user input.
def decode (byte_data)
def encode (char_data)
def hasbyte (byte, byte_data)
def pack (pieces)
def join (chars)
def getheader (headers, key)
Variables
string NULL = '\x00'
Detailed Description
Python2-specific versions of various functions used by stomp.py.
Function Documentation
def stomp.backward2.decode (byte_data)
Referenced by stomp.__main__.StompCLI.do_sendfile(), stomp.utils.parse_frame(), and stomp.transport.BaseTransport.wait_for_connection().
def stomp.backward2.encode (char_data)
Referenced by stomp.adapter.multicast.MulticastTransport.process_frame(), stomp.protocol.Protocol10.send(), stomp.protocol.Protocol11.send(), and stomp.transport.BaseTransport.transmit().
def stomp.backward2.getheader (headers, key)
def stomp.backward2.hasbyte (byte, byte_data)
Referenced by stomp.protocol.Protocol11.send().
def stomp.backward2.input_prompt (prompt)
Get user input.
def stomp.backward2.join (chars)
Referenced by stomp.__main__.StompCLI.do_send(), stomp.__main__.StompCLI.do_sendrec(), stomp.__main__.StompCLI.do_sendreply(), and stomp.backward2.pack().
def stomp.backward2.pack (pieces)
Referenced by stomp.adapter.multicast.MulticastTransport.process_frame(), and stomp.transport.BaseTransport.transmit().
Variable Documentation
string stomp.backward2.NULL = '\x00'