stomp.py: stomp.backward3 Namespace Reference
stomp.backward3 Namespace Reference
Python3-specific versions of various functions used by stomp.py.
Functions
def input_prompt (prompt)
Get user input.
def decode (byte_data)
def encode (char_data)
def hasbyte (byte, byte_data)
def pack (pieces)
def join (chars)
def getheader (headers, key)
Variables
string NULL = b'\x00'
Detailed Description
Python3-specific versions of various functions used by stomp.py.
Function Documentation
def stomp.backward3.decode (byte_data)
Referenced by stomp.backward3.join().
def stomp.backward3.encode (char_data)
Referenced by stomp.backward3.pack().
def stomp.backward3.getheader (headers, key)
def stomp.backward3.hasbyte (byte, byte_data)
def stomp.backward3.input_prompt (prompt)
Get user input.
def stomp.backward3.join (chars)
Referenced by stomp.backward3.pack().
def stomp.backward3.pack (pieces)
Variable Documentation
string stomp.backward3.NULL = b'\x00'